sudo: required
services:
  - docker

before_install:
  - docker build -t badalkodape9623/docker-react -f Dockerfile.dev .

script:
  - docker run badalkodape9623/docker-react npm run test -- --coverage
