sudo: required
services:
  - docker

before_install:
  - docker build -t badalkodape9623/docker-react -f Dockerfile.dev .

script:
  - docker run badalkodape9623/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "DOCKER-REACT"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-447873370974"
  bucket_path: "DOCKER-REACT"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
